headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'Referer': 'https://app.ahrefs.com/v2-site-explorer/top-pages/subdomains?chartInterval=month&compareDate=dontCompare&country=all&showTitles=0&target=https%3A%2F%2Fblog.icodes.tech%2F&volume_type=monthly',
    'Content-Type': 'application/json; charset=utf-8',
    'Origin': 'https://app.ahrefs.com',
    'Connection': 'keep-alive',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'AlexaToolbar-ALX_NS_PH': 'AlexaToolbar/alx-4.0.2',
    'TE': 'trailers',
}
